### ISSUE TITLE
Error after restarting docker container

### ISSUE THREAD

**Issue by danielfomin96** [pluja/Parasitter#112]
I am building a docker image from the latest dev-indep branch (but master does also not work) and it works when starting for the first time. But something breaks after I stop the container and start it then again:
```
Oct 15 10:17:17 docker-compose[927939]: yotter     | INFO  [alembic.runtime.migration] Context impl MySQLImpl.
Oct 15 10:17:17 docker-compose[927939]: yotter     | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Oct 15 10:17:17 docker-compose[927939]: yotter     | ERROR [root] Error: Can't locate revision identified by '135364a870c1'
Oct 15 10:17:17 docker-compose[927939]: yotter exited with code 1
```

docker-compose.yml:
```
version: '3.5'
services:
  mariadb:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: user
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    restart: unless-stopped
    volumes:
     - ./db:/var/lib/mysql
    healthcheck:
     test: ["CMD", "mysqladmin", "-uroot", "-ppass", "ping", "--silent"]
  yotter:
    image: daniel/yotter
    container_name: yotter
    restart: unless-stopped
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      DATABASE_URL: mysql+pymysql://user:pass@mariadb:3306/user
    depends_on:
      - mariadb
    ports:
      - "5000:5000"
    volumes:
      - /usr/src/app/migrations
      - ./yotter-config.json:/usr/src/app/yotter-config.json
```
yotter-config.json:
```
{
        "serverName": "yotter.example.com",
        "nitterInstance": "https://nitter.net/",
        "maxInstanceUsers": 1,
        "serverLocation": "Germany",
        "restrictPublicUsage":true,
        "nginxVideoStream":true,
        "maintenance_mode":false,
        "show_admin_message":false,
        "admin_message_title":"Message from the admin",
        "admin_message":"Message from the admin text"
}
```
